name: Publish subgraphs to Apollo Studio

on:
  workflow_dispatch:
  workflow_call:

env:
  GEN: "workshop"
  APOLLO_KEY: ${{ vars.TOKEN }}
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rover
      run: | 
        curl -sSL https://rover.apollo.dev/nix/v0.19.0 | sh
        echo "$HOME/.rover/bin" >> $GITHUB_PATH

    - name: Rover Subgraph Publish Products
      run: | 
        rover subgraph publish ${{vars.ACTOR}}${{ env.GEN }}@current \
          --name products \
          --convert \
          --routing-url https://subgraph-products-j3nprurqka-ue.a.run.app \
          --schema ./products-schema.graphql

    - name: Rover Subgraph Publish Orders
      run: | 
        rover subgraph publish ${{vars.ACTOR}}${{ env.GEN }}@current \
          --name orders \
          --routing-url https://subgraph-orders-j3nprurqka-ue.a.run.app \
          --schema ./orders-schema.graphql

    - name: Rover Subgraph Publish Customers
      run: |
        rover subgraph publish ${{vars.ACTOR}}${{ env.GEN }}@current \
          --name customers \
          --routing-url https://subgraph-customers-j3nprurqka-ue.a.run.app \
          --schema ./final/customers-schema.graphql